[tox]
envlist = py312, linting
skipsdist = True

[testenv]
skip_install = True
deps =
  -rrequirements.txt
  -rtest/test_requirements.txt

[testenv:py312]
setenv =
  AS_CHUNK_SIZE=100
  ASSETS_DIR=assets
  LAST_FETCHED_FILEPATH=last_fetched_timestamp.txt
commands =
	coverage run -m pytest -s
	coverage report -m

[testenv:linting]
basepython = python3
deps = pre-commit
commands =
    pre-commit run --all-files

[flake8]
application-import-names = flake8
select = B, C, E, F, W, B950
import-order-style = pep8
max-complexity = 10
ignore =
  # Line too long (82 > 79 characters).
	E501,
  # Blank line at end of file
	W391,